/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package livraria.view.livros;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import livraria.models.Livro;
import livraria.controllers.LivroController;
import livraria.models.Autor;
import livraria.controllers.AutorController;

/**
 *
 * @author admin
 */
public class BookRegistration extends javax.swing.JFrame {

    /**
     * Creates new form BookRegistration
     */
    public BookRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoLivro = new javax.swing.JTextField();
        nomeLivro = new javax.swing.JTextField();
        linguaLivro = new javax.swing.JTextField();
        anoLivro = new javax.swing.JTextField();
        buttonAddLivro = new javax.swing.JButton();
        autorCbb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Livro");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        codigoLivro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        codigoLivro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoLivro.setText("Código");
        codigoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoLivroActionPerformed(evt);
            }
        });

        nomeLivro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        nomeLivro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeLivro.setText("Nome");
        nomeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeLivroActionPerformed(evt);
            }
        });

        linguaLivro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        linguaLivro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linguaLivro.setText("Língua escrita");
        linguaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linguaLivroActionPerformed(evt);
            }
        });

        anoLivro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        anoLivro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anoLivro.setText("Ano");
        anoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoLivroActionPerformed(evt);
            }
        });

        buttonAddLivro.setText("Cadastrar Livro");
        buttonAddLivro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153)));
        buttonAddLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddLivroActionPerformed(evt);
            }
        });

        autorCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o autor" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autorCbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(linguaLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(nomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(codigoLivro)
                    .addComponent(buttonAddLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(codigoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linguaLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autorCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAddLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoLivroActionPerformed

    private void nomeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeLivroActionPerformed

    private void linguaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linguaLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linguaLivroActionPerformed

    private void anoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoLivroActionPerformed

    private void buttonAddLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddLivroActionPerformed
        Livro livro = new Livro();
        LivroController controllerLivro = new LivroController();
        
        livro.setNome(nomeLivro.getText());
        livro.setCodigo(codigoLivro.getText());
        livro.setAno(Integer.parseInt(anoLivro.getText()));
        livro.setLingua(linguaLivro.getText());
        livro.setAutor((String) autorCbb.getSelectedItem());
        
        boolean result = controllerLivro.create(livro);
        
        if(result){
            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
            this.show(false);
        }else{
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar o livro!");
        }
    }//GEN-LAST:event_buttonAddLivroActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        AutorController controllerAutor = new AutorController();
        
        ArrayList<Autor> autores = controllerAutor.showAll();
        
        for(Autor autor: autores){
            autorCbb.addItem(autor.getNome());
        }
    }//GEN-LAST:event_jLabel1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoLivro;
    private javax.swing.JComboBox<String> autorCbb;
    private javax.swing.JButton buttonAddLivro;
    private javax.swing.JTextField codigoLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField linguaLivro;
    private javax.swing.JTextField nomeLivro;
    // End of variables declaration//GEN-END:variables
}
