/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package livraria.view.autor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import livraria.models.Autor;
import livraria.controllers.AutorController;
import java.sql.Date;
import livraria.view.autor.AuthorUpdate;

/**
 *
 * @author admin
 */
public class RentAuthor extends javax.swing.JFrame {

    /**
     * Creates new form RentAuthor
     */
    public RentAuthor() {
        initComponents();
    }
    
    public void insertTable(ArrayList<Autor> autores){
        DefaultTableModel model = (DefaultTableModel) tableAutor.getModel();
        
        for(int i = 0; i < model.getRowCount(); i++){
            model.removeRow(i);
        }
        
        for(Autor autor: autores){
            Object[] rowData = {
                autor.getId(),
                autor.getNome(),
                autor.getData_nasc(),
                autor.getNacionalidade(),
                autor.getBiografia(),
            };
            
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAutor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonEditar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Data Nascimento", "Nacionalidade", "Biografia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAutor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableAutorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAutor);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Autores Cadastrados");

        buttonEditar.setText("Atualizar");
        buttonEditar.setEnabled(false);
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonRemover.setText("Excluir");
        buttonRemover.setEnabled(false);
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRemover)
                    .addComponent(buttonEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableAutorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableAutorAncestorAdded
        AutorController autorController = new AutorController();
        ArrayList<Autor> autores = autorController.showAll();
        insertTable(autores);
    }//GEN-LAST:event_tableAutorAncestorAdded

    private void tableAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAutorMouseClicked
        int selectedRow = tableAutor.getSelectedRow();
        
        if(selectedRow != -1){
            buttonEditar.setEnabled(true);
            buttonRemover.setEnabled(true);
        }
    }//GEN-LAST:event_tableAutorMouseClicked

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        int selectedRow = tableAutor.getSelectedRow();
        
        int idAutor = (int) tableAutor.getValueAt(selectedRow, 0);
        
        Autor autor = new Autor();
        autor.setId(idAutor);
        
        AutorController autorController = new AutorController();
        
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?");
        
        if(escolha == 0){
            boolean result = autorController.delete(autor);
        
            if(result){
                 JOptionPane.showMessageDialog(null, "Autor excluído com sucesso!");
            } else {
                 JOptionPane.showMessageDialog(null, "Erro ao excluir autor!");
            }
        }
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        Autor autor = new Autor();
        int selectedRow = tableAutor.getSelectedRow();
        
        autor.setId((int) tableAutor.getValueAt(selectedRow, 0));
        autor.setNome((String) tableAutor.getValueAt(selectedRow, 1));
        autor.setNacionalidade((String) tableAutor.getValueAt(selectedRow, 3));
        autor.setData_nasc((Date) tableAutor.getValueAt(selectedRow, 2));
        autor.setBiografia((String) tableAutor.getValueAt(selectedRow, 4));
        
        new AuthorUpdate(autor).show();
    }//GEN-LAST:event_buttonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentAuthor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAutor;
    // End of variables declaration//GEN-END:variables
}
